[package]
name = "workshop_uploader"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name="4wu"
path="src/main.rs"

[dependencies]
steamworks = "0.9.0"
iced = "0.6"
native-dialog = "0.6.3"
